/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.mwaleria.safecommunicator.client.gui;

import pl.mwaleria.safecommunicator.client.ClientManager;
import pl.mwaleria.safecommunicator.client.ConnectResponse;

/**
 *
 * @author waler
 */
public class LoginFrame extends javax.swing.JFrame {

	private final ClientManager clientManager;

	/**
	 * Creates new form LoginFrame
	 * 
	 * @param clientManager
	 */
	public LoginFrame(ClientManager clientManager) {
		this.clientManager = clientManager;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		textServerHost = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		testServerPort = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		testUserName = new javax.swing.JTextField();
		textRandom = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		buttonLogin = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("SAFE COMMUNICATOR");
		setResizable(false);

		jLabel1.setText("Server Address");

		jLabel2.setText("Server Port");

		jLabel3.setText("User Name");

		textRandom.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textRandomActionPerformed(evt);
			}
		});

		jLabel4.setText("Random text for keys generation");

		buttonLogin.setText("Sign in");
		buttonLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonLoginActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(testUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 188,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(textServerHost, javax.swing.GroupLayout.PREFERRED_SIZE, 188,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel4).addComponent(textRandom)
														.addComponent(buttonLogin, javax.swing.GroupLayout.DEFAULT_SIZE,
																280, Short.MAX_VALUE))
												.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(testServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 188,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addComponent(textServerHost, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(29, 29, 29)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(testServerPort, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3)
						.addComponent(testUserName, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(jLabel4).addGap(18, 18, 18)
				.addComponent(textRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18).addComponent(buttonLogin).addContainerGap()));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void textRandomActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textRandomActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textRandomActionPerformed

	private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonLoginActionPerformed
		if (!isContentValid()) {
			return;
		}
		ConnectResponse resp = clientManager.connectToServer(textServerHost.getText(), testServerPort.getText(),
				testUserName.getText(), textRandom.getText());
		if (resp == ConnectResponse.SUCCESS) {
			this.setVisible(false);
			clientManager.openCommunicationForm();
		}

	}// GEN-LAST:event_buttonLoginActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField testServerPort;
	private javax.swing.JTextField testUserName;
	private javax.swing.JTextField textRandom;
	private javax.swing.JTextField textServerHost;
	// End of variables declaration//GEN-END:variables

	private boolean isContentValid() {
		return true;
	}
}
